### ISSUE TITLE
Module parse failed: Unexpected token

### ISSUE THREAD

**Issue by msobalvarro** [tatethurston/react-itertools#2]
![2021-12-16_10-52](https://user-images.githubusercontent.com/31081380/146414419-2e9c512b-f63c-47c5-8276-a523f7f166a9.png)

I don't really know if I'm doing something wrong, but I think this compile error belongs to react-itertools

**Comment by tatethurston** [comment]
Hey @msobalvarro , this is because your parser is running a JS version older than ES2020 when the null ish coalescing  ‘??’ operator was introduced.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator

I’m happy to target an older ES version, I’ll follow up with an npm publish.

**Comment by msobalvarro** [comment]
it would be very useful to point to an older ES version

**Comment by tatethurston** [comment]
I published 0.0.6 to npm @msobalvarro. Let me know if you run into any issues!
